name: Update SVG

on:
    schedule:
        - cron: "0 0 * * *"
    workflow_dispatch:

jobs:
    update:
        runs-on: ubuntu-latest
        permissions:
            contents: write

        steps:
            - name: Checkout repository
              uses: actions/checkout@v4

            - name: Setup Deno
              uses: denoland/setup-deno@v2
              with:
                  deno-version: v2.x

            - name: Download stats image
              run: deno task download-stats-image

            - name: Create Ranking Image
              run: deno task create-ranking-image

            - name: deno fmt
              run: deno fmt

            - name: Commit and push if any files changed
              run: |
                  if git diff --quiet; then
                    echo "No changes to commit."
                    exit 0
                  fi

                  git config user.name "github-actions[bot]"
                  git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
                  git add -A
                  git commit -m "chore: update stats.svg"
                  git push
